-- 1. Create Tables

-- Companies Table (Profiles)
-- Note: We link this to auth.users
CREATE TABLE IF NOT EXISTS public.companies (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL,
    cnpj TEXT UNIQUE NOT NULL,
    email TEXT UNIQUE NOT NULL,
    whatsapp TEXT,
    logo_url TEXT,
    subscription_status TEXT DEFAULT 'inactive' CHECK (subscription_status IN ('active', 'inactive', 'canceled')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Jobs Table
CREATE TABLE IF NOT EXISTS public.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id UUID REFERENCES public.companies(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    cbo_code TEXT,
    cbo_name TEXT,
    description TEXT,
    requirements TEXT,
    location TEXT,
    type TEXT,
    salary TEXT,
    deadline DATE,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'closed')),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Candidates Table
CREATE TABLE IF NOT EXISTS public.candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT REFERENCES public.jobs(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT NOT NULL,
    resume_url TEXT,
    message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Interviews Table
CREATE TABLE IF NOT EXISTS public.interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT REFERENCES public.candidates(id) ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL,
    time TIME NOT NULL,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interviews ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies

-- Companies Policies
CREATE POLICY "Public profiles are viewable by everyone" ON public.companies
    FOR SELECT USING (true);

CREATE POLICY "Users can update their own company profile" ON public.companies
    FOR UPDATE USING (auth.uid() = id);

-- Jobs Policies
CREATE POLICY "Jobs are viewable by everyone" ON public.jobs
    FOR SELECT USING (true);

CREATE POLICY "Companies can insert their own jobs" ON public.jobs
    FOR INSERT WITH CHECK (auth.uid() = company_id);

CREATE POLICY "Companies can update their own jobs" ON public.jobs
    FOR UPDATE USING (auth.uid() = company_id);

-- Candidates Policies
CREATE POLICY "Candidates can apply to jobs" ON public.candidates
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Companies can view candidates for their jobs" ON public.candidates
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.jobs
            WHERE jobs.id = candidates.job_id
            AND jobs.company_id = auth.uid()
        )
    );

-- Interviews Policies
CREATE POLICY "Companies can manage interviews for their candidates" ON public.interviews
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.candidates
            JOIN public.jobs ON candidates.job_id = jobs.id
            WHERE candidates.id = interviews.candidate_id
            AND jobs.company_id = auth.uid()
        )
    );

-- 4. Storage Buckets Setup
-- Note: These usually need to be created via the Supabase Dashboard, 
-- but these policies will work once the buckets 'resumes' and 'logos' exist.

-- Allow public uploads to resumes
CREATE POLICY "Public Upload Resumes" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'resumes');

-- Allow public viewing of resumes (for companies to see them)
-- In a production app, you'd restrict this to the specific company.
CREATE POLICY "Public View Resumes" ON storage.objects
    FOR SELECT USING (bucket_id = 'resumes');

-- Allow public viewing of logos
CREATE POLICY "Public View Logos" ON storage.objects
    FOR SELECT USING (bucket_id = 'logos');

-- Allow companies to upload their own logos
CREATE POLICY "Companies Upload Logos" ON storage.objects
    FOR INSERT WITH CHECK (bucket_id = 'logos' AND auth.role() = 'authenticated');

-- 5. Trigger for New User Profile
-- This automatically creates a company profile when a new user signs up
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.companies (id, name, cnpj, email, whatsapp, subscription_status)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'name', 'Minha Empresa'),
    COALESCE(NEW.raw_user_meta_data->>'cnpj', '00000000000000'),
    NEW.email,
    NEW.raw_user_meta_data->>'whatsapp',
    'inactive'
  )
  ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    cnpj = EXCLUDED.cnpj,
    email = EXCLUDED.email,
    whatsapp = EXCLUDED.whatsapp;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
